import org.junit.Test;

import java.io.Reader;
import java.io.StringReader;

import investment.controller.InvestmentController;
import investment.controller.InvestmentControllerImpl;
import investment.model.PortfolioManagementImpl;
import investment.view.InvestmentView;
import investment.view.InvestmentViewImpl;

import static junit.framework.TestCase.assertEquals;

public class InvestmentControllerModelTest2 {

  @Test
  public void testOption7WI() {
    StringBuffer out = new StringBuffer();
    Reader in = new StringReader("F 1 myPortfolio 2 myPortfolio 1290.08 30 2016-12-29 "
            + "13:00:23 WFC"
            + " 3 myPortfolio 4 myPortfolio 2018-11-13 5 myPortfolio 2018-11-13 2 myPortfolio "
            + "4000 60 2010-12-29 15:00:23 MSFT 2 myPortfolio 2000 20 2011-02-25 10:05:23 BEN 3 "
            + "myPortfolio 7 1 strategy1 34343 23 2018-11-13 MSFT,GOOG 40,60 q");
    PortfolioManagementImpl portfolioManagement = new PortfolioManagementImpl();
    InvestmentView view = new InvestmentViewImpl(in, out);
    InvestmentController controller = new InvestmentControllerImpl(portfolioManagement, view);
    controller.execute();
    assertEquals("Enter the data source: \n"
            + "A: API\n"
            + "F: Files\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Portfolio myPortfolio is created\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the amount(in dollars)\n"
            + "Enter the commission amount\n"
            + "Enter the Date\n"
            + "Enter the Time\n"
            + "Enter the ticker name.\n"
            + "Stock bought successfully\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Ticker symbol: WFC, Number of shares: 23, Date of purchase: 2016-12-29\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the Date\n"
            + "1291.32\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the Date\n"
            + "1213.02\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the amount(in dollars)\n"
            + "Enter the commission amount\n"
            + "Enter the Date\n"
            + "Enter the Time\n"
            + "Enter the ticker name.\n"
            + "Stock bought successfully\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the amount(in dollars)\n"
            + "Enter the commission amount\n"
            + "Enter the Date\n"
            + "Enter the Time\n"
            + "Enter the ticker name.\n"
            + "Stock bought successfully\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Ticker symbol: WFC, Number of shares: 23, Date of purchase: 2016-12-29\n"
            + "Ticker symbol: MSFT, Number of shares: 143, Date of purchase: 2010-12-29\n"
            + "Ticker symbol: BEN, Number of shares: 16, Date of purchase: 2011-02-25\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "1.Weighted Investment\n"
            + "2.Equally Weighted Investment\n"
            + "3.Dollar Cost Averaging\n"
            + "Enter your choice.Enter the name of the Strategy to be created.\n"
            + "Enter the amount(in dollars)\n"
            + "Enter the commission amount\n"
            + "Enter the Date\n"
            + "Enter the list of tickers:\n"
            + "Enter the list of weights:\n"
            + "Strategy strategy1 created successfully.\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Quitting the application", out.toString());
  }

  @Test
  public void testOption7WICostBasis() {
    StringBuffer out = new StringBuffer();
    Reader in = new StringReader("F 1 myPortfolio 2 myPortfolio 1290.08 30 2016-12-29 "
            + "13:00:23 WFC"
            + " 3 myPortfolio 4 myPortfolio 2018-11-13 5 myPortfolio 2018-11-13 2 myPortfolio "
            + "4000 60 2010-12-29 15:00:23 MSFT 2 myPortfolio 2000 20 2011-02-25 10:05:23 BEN 3 "
            + "myPortfolio 7 1 strategy1 34343 23 2018-11-13 MSFT,GOOG 40,60 8 strategy1 "
            + "myportfolio 4 myportfolio 2017-11-11 4 myportfolio 2018-11-13  4 myportfolio "
            + "2018-11-19 q");
    PortfolioManagementImpl portfolioManagement = new PortfolioManagementImpl();
    InvestmentView view = new InvestmentViewImpl(in, out);
    InvestmentController controller = new InvestmentControllerImpl(portfolioManagement, view);
    controller.execute();
    assertEquals("Enter the data source: \n"
            + "A: API\n"
            + "F: Files\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Portfolio myPortfolio is created\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the amount(in dollars)\n"
            + "Enter the commission amount\n"
            + "Enter the Date\n"
            + "Enter the Time\n"
            + "Enter the ticker name.\n"
            + "Stock bought successfully\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Ticker symbol: WFC, Number of shares: 23, Date of purchase: 2016-12-29\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the Date\n"
            + "1291.32\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the Date\n"
            + "1213.02\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the amount(in dollars)\n"
            + "Enter the commission amount\n"
            + "Enter the Date\n"
            + "Enter the Time\n"
            + "Enter the ticker name.\n"
            + "Stock bought successfully\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the amount(in dollars)\n"
            + "Enter the commission amount\n"
            + "Enter the Date\n"
            + "Enter the Time\n"
            + "Enter the ticker name.\n"
            + "Stock bought successfully\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Ticker symbol: WFC, Number of shares: 23, Date of purchase: 2016-12-29\n"
            + "Ticker symbol: MSFT, Number of shares: 143, Date of purchase: 2010-12-29\n"
            + "Ticker symbol: BEN, Number of shares: 16, Date of purchase: 2011-02-25\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "1.Weighted Investment\n"
            + "2.Equally Weighted Investment\n"
            + "3.Dollar Cost Averaging\n"
            + "Enter your choice.Enter the name of the Strategy to be created.\n"
            + "Enter the amount(in dollars)\n"
            + "Enter the commission amount\n"
            + "Enter the Date\n"
            + "Enter the list of tickers:\n"
            + "Enter the list of weights:\n"
            + "Strategy strategy1 created successfully.\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Strategy to be created.\n"
            + "Enter the name of the Portfolio\n"
            + "Strategy strategy1 applied successfully to myportfolio\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the Date\n"
            + "0.0\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the Date\n"
            + "33419.270000000004\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the Date\n"
            + "33419.270000000004\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Quitting the application", out.toString());
  }

  @Test
  public void testOption7WICurrentValue() {
    StringBuffer out = new StringBuffer();
    Reader in = new StringReader("F 1 myPortfolio 2 myPortfolio 1290.08 30 2016-12-29 "
            + "13:00:23 WFC"
            + " 3 myPortfolio 4 myPortfolio 2018-11-13 5 myPortfolio 2018-11-13 2 myPortfolio "
            + "4000 60 2010-12-29 15:00:23 MSFT 2 myPortfolio 2000 20 2011-02-25 10:05:23 BEN 3 "
            + "myPortfolio 7 1 strategy1 34343 23 2018-11-13 MSFT,GOOG 40,60 8 strategy1 "
            + "myportfolio 5 myportfolio 2017-11-11 5 myportfolio 2018-11-13 5 myportfolio "
            + "2018-11-19 q");
    PortfolioManagementImpl portfolioManagement = new PortfolioManagementImpl();
    InvestmentView view = new InvestmentViewImpl(in, out);
    InvestmentController controller = new InvestmentControllerImpl(portfolioManagement, view);
    controller.execute();
    assertEquals("Enter the data source: \n"
            + "A: API\n"
            + "F: Files\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Portfolio myPortfolio is created\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the amount(in dollars)\n"
            + "Enter the commission amount\n"
            + "Enter the Date\n"
            + "Enter the Time\n"
            + "Enter the ticker name.\n"
            + "Stock bought successfully\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Ticker symbol: WFC, Number of shares: 23, Date of purchase: 2016-12-29\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the Date\n"
            + "1291.32\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the Date\n"
            + "1213.02\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the amount(in dollars)\n"
            + "Enter the commission amount\n"
            + "Enter the Date\n"
            + "Enter the Time\n"
            + "Enter the ticker name.\n"
            + "Stock bought successfully\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the amount(in dollars)\n"
            + "Enter the commission amount\n"
            + "Enter the Date\n"
            + "Enter the Time\n"
            + "Enter the ticker name.\n"
            + "Stock bought successfully\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Ticker symbol: WFC, Number of shares: 23, Date of purchase: 2016-12-29\n"
            + "Ticker symbol: MSFT, Number of shares: 143, Date of purchase: 2010-12-29\n"
            + "Ticker symbol: BEN, Number of shares: 16, Date of purchase: 2011-02-25\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "1.Weighted Investment\n"
            + "2.Equally Weighted Investment\n"
            + "3.Dollar Cost Averaging\n"
            + "Enter your choice.Enter the name of the Strategy to be created.\n"
            + "Enter the amount(in dollars)\n"
            + "Enter the commission amount\n"
            + "Enter the Date\n"
            + "Enter the list of tickers:\n"
            + "Enter the list of weights:\n"
            + "Strategy strategy1 created successfully.\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Strategy to be created.\n"
            + "Enter the name of the Portfolio\n"
            + "Strategy strategy1 applied successfully to myportfolio\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the Date\n"
            + "0.0\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the Date\n"
            + "33373.270000000004\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the Date\n"
            + "32771.36\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Quitting the application", out.toString());
  }

  @Test
  public void testOption7EW() {
    StringBuffer out = new StringBuffer();
    Reader in = new StringReader("F 1 myPortfolio 2 myPortfolio 1290.08 30 2016-12-29 "
            + "13:00:23 WFC"
            + " 3 myPortfolio 4 myPortfolio 2018-11-13 5 myPortfolio 2018-11-13 2 myPortfolio "
            + "4000 60 2010-12-29 15:00:23 MSFT 2 myPortfolio 2000 20 2011-02-25 10:05:23 BEN 3 "
            + "myPortfolio 7 2 strategy2 34343 23 2018-11-13 q");
    PortfolioManagementImpl portfolioManagement = new PortfolioManagementImpl();
    InvestmentView view = new InvestmentViewImpl(in, out);
    InvestmentController controller = new InvestmentControllerImpl(portfolioManagement, view);
    controller.execute();
    assertEquals("Enter the data source: \n"
            + "A: API\n"
            + "F: Files\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Portfolio myPortfolio is created\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the amount(in dollars)\n"
            + "Enter the commission amount\n"
            + "Enter the Date\n"
            + "Enter the Time\n"
            + "Enter the ticker name.\n"
            + "Stock bought successfully\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Ticker symbol: WFC, Number of shares: 23, Date of purchase: 2016-12-29\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the Date\n"
            + "1291.32\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the Date\n"
            + "1213.02\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the amount(in dollars)\n"
            + "Enter the commission amount\n"
            + "Enter the Date\n"
            + "Enter the Time\n"
            + "Enter the ticker name.\n"
            + "Stock bought successfully\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the amount(in dollars)\n"
            + "Enter the commission amount\n"
            + "Enter the Date\n"
            + "Enter the Time\n"
            + "Enter the ticker name.\n"
            + "Stock bought successfully\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Ticker symbol: WFC, Number of shares: 23, Date of purchase: 2016-12-29\n"
            + "Ticker symbol: MSFT, Number of shares: 143, Date of purchase: 2010-12-29\n"
            + "Ticker symbol: BEN, Number of shares: 16, Date of purchase: 2011-02-25\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "1.Weighted Investment\n"
            + "2.Equally Weighted Investment\n"
            + "3.Dollar Cost Averaging\n"
            + "Enter your choice.Enter the name of the Strategy to be created.\n"
            + "Enter the amount(in dollars)\n"
            + "Enter the commission amount\n"
            + "Enter the Date\n"
            + "Strategy strategy2 created successfully.\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Quitting the application", out.toString());
  }

  @Test
  public void testOption7DC() {
    StringBuffer out = new StringBuffer();
    Reader in = new StringReader("F 1 myPortfolio 2 myPortfolio 1290.08 30 2016-12-29 "
            + "13:00:23 WFC"
            + " 3 myPortfolio 4 myPortfolio 2018-11-13 5 myPortfolio 2018-11-13 2 myPortfolio "
            + "4000 60 2010-12-29 15:00:23 MSFT 2 myPortfolio 2000 20 2011-02-25 10:05:23 BEN 3 "
            + "myPortfolio 7 3 strategy3 2018-11-13 n 34343 45 10 MSFT,GOOG 40,60 q");
    PortfolioManagementImpl portfolioManagement = new PortfolioManagementImpl();
    InvestmentView view = new InvestmentViewImpl(in, out);
    InvestmentController controller = new InvestmentControllerImpl(portfolioManagement, view);
    controller.execute();
    assertEquals("Enter the data source: \n"
            + "A: API\n"
            + "F: Files\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Portfolio myPortfolio is created\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the amount(in dollars)\n"
            + "Enter the commission amount\n"
            + "Enter the Date\n"
            + "Enter the Time\n"
            + "Enter the ticker name.\n"
            + "Stock bought successfully\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Ticker symbol: WFC, Number of shares: 23, Date of purchase: 2016-12-29\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the Date\n"
            + "1291.32\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the Date\n"
            + "1213.02\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the amount(in dollars)\n"
            + "Enter the commission amount\n"
            + "Enter the Date\n"
            + "Enter the Time\n"
            + "Enter the ticker name.\n"
            + "Stock bought successfully\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the amount(in dollars)\n"
            + "Enter the commission amount\n"
            + "Enter the Date\n"
            + "Enter the Time\n"
            + "Enter the ticker name.\n"
            + "Stock bought successfully\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Ticker symbol: WFC, Number of shares: 23, Date of purchase: 2016-12-29\n"
            + "Ticker symbol: MSFT, Number of shares: 143, Date of purchase: 2010-12-29\n"
            + "Ticker symbol: BEN, Number of shares: 16, Date of purchase: 2011-02-25\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "1.Weighted Investment\n"
            + "2.Equally Weighted Investment\n"
            + "3.Dollar Cost Averaging\n"
            + "Enter your choice.Enter the name of the Strategy to be created.\n"
            + "Enter the Date\n"
            + "Enter the end date. Enter n if the investment is currently running: \n"
            + "Enter the amount(in dollars)\n"
            + "Enter the commission amount\n"
            + "Enter the frequency(in days) to buy the stocks.\n"
            + "Enter the list of tickers:\n"
            + "Enter the list of weights:\n"
            + "Strategy strategy3 created successfully.\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Quitting the application", out.toString());
  }


  @Test
  public void testOption8() {
    StringBuffer out = new StringBuffer();
    Reader in = new StringReader("F 10 myPortfolio 12 WI_strategy1 8 strategy1 myPortfolio 3 "
            + "myPortfolio q");
    PortfolioManagementImpl portfolioManagement = new PortfolioManagementImpl();
    InvestmentView view = new InvestmentViewImpl(in, out);
    InvestmentController controller = new InvestmentControllerImpl(portfolioManagement, view);
    controller.execute();
    assertEquals("Enter the data source: \n"
            + "A: API\n"
            + "F: Files\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Portfolio myPortfolio retrieved successfully.\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "1.Weighted Investment\n"
            + "2.Equally Weighted Investment\n"
            + "3.Dollar Cost Averaging\n"
            + "Enter your choice.Portfolio WI_strategy1 retrieved successfully.\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Strategy to be created.\n"
            + "Enter the name of the Portfolio\n"
            + "Strategy strategy1 applied successfully to myPortfolio\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Ticker symbol: WFC, Number of shares: 23, Date of purchase: 2016-12-29\n"
            + "Ticker symbol: MSFT, Number of shares: 128, Date of purchase: 2018-11-13\n"
            + "Ticker symbol: GOOG, Number of shares: 19, Date of purchase: 2018-11-13\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Quitting the application", out.toString());
  }


  @Test
  public void testOption9() {
    StringBuffer out = new StringBuffer();
    Reader in = new StringReader("F 1 myPortfolio 2 myPortfolio 1290.08 30 2016-12-29 13:00:23 "
            + "WFC 9 myPortfolio q");
    PortfolioManagementImpl portfolioManagement = new PortfolioManagementImpl();
    InvestmentView view = new InvestmentViewImpl(in, out);
    InvestmentController controller = new InvestmentControllerImpl(portfolioManagement, view);
    controller.execute();
    assertEquals("Enter the data source: \n"
            + "A: API\n"
            + "F: Files\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Portfolio myPortfolio is created\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the amount(in dollars)\n"
            + "Enter the commission amount\n"
            + "Enter the Date\n"
            + "Enter the Time\n"
            + "Enter the ticker name.\n"
            + "Stock bought successfully\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Portfolio myPortfolio saved successfully.\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Quitting the application", out.toString());
  }


  @Test
  public void testOption10() {
    StringBuffer out = new StringBuffer();
    Reader in = new StringReader("F 10 myPortfolio 3 myPortfolio q");
    PortfolioManagementImpl portfolioManagement = new PortfolioManagementImpl();
    InvestmentView view = new InvestmentViewImpl(in, out);
    InvestmentController controller = new InvestmentControllerImpl(portfolioManagement, view);
    controller.execute();
    assertEquals("Enter the data source: \n"
            + "A: API\n"
            + "F: Files\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Portfolio myPortfolio retrieved successfully.\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Ticker symbol: WFC, Number of shares: 23, Date of purchase: 2016-12-29\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Quitting the application", out.toString());
  }


  @Test
  public void testOption11() {
    StringBuffer out = new StringBuffer();
    Reader in = new StringReader("F 1 myPortfolio 2 myPortfolio 1290.08 30 2016-12-29 "
            + "13:00:23 WFC"
            + " 3 myPortfolio 4 myPortfolio 2018-11-13 5 myPortfolio 2018-11-13 2 myPortfolio "
            + "4000 60 2010-12-29 15:00:23 MSFT 2 myPortfolio 2000 20 2011-02-25 10:05:23 BEN 3 "
            + "myPortfolio 7 1 strategy1 34343 23 2018-11-13 MSFT,GOOG 40,60 11 strategy1 q");
    PortfolioManagementImpl portfolioManagement = new PortfolioManagementImpl();
    InvestmentView view = new InvestmentViewImpl(in, out);
    InvestmentController controller = new InvestmentControllerImpl(portfolioManagement, view);
    controller.execute();
    assertEquals("Enter the data source: \n"
            + "A: API\n"
            + "F: Files\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Portfolio myPortfolio is created\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the amount(in dollars)\n"
            + "Enter the commission amount\n"
            + "Enter the Date\n"
            + "Enter the Time\n"
            + "Enter the ticker name.\n"
            + "Stock bought successfully\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Ticker symbol: WFC, Number of shares: 23, Date of purchase: 2016-12-29\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the Date\n"
            + "1291.32\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the Date\n"
            + "1213.02\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the amount(in dollars)\n"
            + "Enter the commission amount\n"
            + "Enter the Date\n"
            + "Enter the Time\n"
            + "Enter the ticker name.\n"
            + "Stock bought successfully\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the amount(in dollars)\n"
            + "Enter the commission amount\n"
            + "Enter the Date\n"
            + "Enter the Time\n"
            + "Enter the ticker name.\n"
            + "Stock bought successfully\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Ticker symbol: WFC, Number of shares: 23, Date of purchase: 2016-12-29\n"
            + "Ticker symbol: MSFT, Number of shares: 143, Date of purchase: 2010-12-29\n"
            + "Ticker symbol: BEN, Number of shares: 16, Date of purchase: 2011-02-25\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "1.Weighted Investment\n"
            + "2.Equally Weighted Investment\n"
            + "3.Dollar Cost Averaging\n"
            + "Enter your choice.Enter the name of the Strategy to be created.\n"
            + "Enter the amount(in dollars)\n"
            + "Enter the commission amount\n"
            + "Enter the Date\n"
            + "Enter the list of tickers:\n"
            + "Enter the list of weights:\n"
            + "Strategy strategy1 created successfully.\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Strategy to be created.\n"
            + "Strategy strategy1 saved successfully.\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Quitting the application", out.toString());
  }

  @Test
  public void testOption12() {
    StringBuffer out = new StringBuffer();
    Reader in = new StringReader("F 1 myPortfolio 2 myPortfolio 1290.08 30 2016-12-29 "
            + "13:00:23 WFC"
            + " 3 myPortfolio 12 WI_strategy1 q");
    PortfolioManagementImpl portfolioManagement = new PortfolioManagementImpl();
    InvestmentView view = new InvestmentViewImpl(in, out);
    InvestmentController controller = new InvestmentControllerImpl(portfolioManagement, view);
    controller.execute();
    assertEquals("Enter the data source: \n"
            + "A: API\n"
            + "F: Files\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Portfolio myPortfolio is created\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Enter the amount(in dollars)\n"
            + "Enter the commission amount\n"
            + "Enter the Date\n"
            + "Enter the Time\n"
            + "Enter the ticker name.\n"
            + "Stock bought successfully\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Enter the name of the Portfolio\n"
            + "Ticker symbol: WFC, Number of shares: 23, Date of purchase: 2016-12-29\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "1.Weighted Investment\n"
            + "2.Equally Weighted Investment\n"
            + "3.Dollar Cost Averaging\n"
            + "Enter your choice.Portfolio WI_strategy1 retrieved successfully.\n"
            + "1.Create a new portfolio\n"
            + "2.Buy Stock\n"
            + "3.Examine Portfolio\n"
            + "4.Get Cost Basis of a Portfolio\n"
            + "5.Get current value of a portfolio\n"
            + "6.Get all portfolio names\n"
            + "7.Create a Strategy\n"
            + "8.Apply a strategy to a portfolio stocks\n"
            + "9.Save a Portfolio to file\n"
            + "10.Retrieve portfolio from file\n"
            + "11.Save Strategy to file\n"
            + "12.Retrieve Strategy from file\n"
            + "Q.Quit\n"
            + "Enter your choice.\n"
            + "Quitting the application", out.toString());
  }

}
